### ISSUE TITLE
ARM64

### ISSUE THREAD

**Issue by hlaueriksson** [Darkdriller/PowerToys-Run-LocalLLm#1]
I'll guess Ollama has no ARM64 support.
It could be nice to write in the readme that this is the reason why Local LLM does not have an `ARM64` release.

**Comment by Darkdriller** [comment]
Hi @hlaueriksson. Please find the find the Note [here](https://github.com/Darkdriller/PowerToys-Run-LocalLLm/tree/v1.0.2?tab=readme-ov-file#note). Also if you wanted to checkout there is a workaround currently for ARM64 build for ollama on windows under [development](https://github.com/hmartinez82/ollama/blob/win_arm64_docs/docs/development.md#windows-on-arm-arm64). It is just for windows 11 right now and its unknown if it will be released for windows 10.
