### ISSUE TITLE
Newtonsoft.Json

### ISSUE THREAD

**Issue by hlaueriksson** [Darkdriller/PowerToys-Run-LocalLLm#2]
I think you can get rid of the `Newtonsoft.Json.dll` in the release zip, if you depend on `System.Text.Json` instead.

If you use the same version as in this file:
https://github.com/microsoft/PowerToys/blob/2a8e211cfd1d329b35fad043e5d476c47ce36fab/Directory.Packages.props#L80

Then you don't need to include dependencies in the the plugin folder and you don't need to use `DynamicLoading`.

**Comment by Darkdriller** [comment]
Hi @hlaueriksson. You can checkout the new release [here](https://github.com/Darkdriller/PowerToys-Run-LocalLLm/releases/tag/v1.0.2). I have removed the dependency for newtonsoft. Thanks for the feedback, It reduced the size considerably too.
